/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AI: typeof import('./components/AI.vue')['default']
    BeHeader: typeof import('./components/common/be-header.vue')['default']
    NotificationListener: typeof import('./components/NotificationListener.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/common/svg-icon.vue')['default']
  }
}
