/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./components/add-cash.vue')['default']
    AddCash: typeof import('./components/add-cash.vue')['default']
    BeTabs: typeof import('./components/common/be-tabs.vue')['default']
    Daa: typeof import('./components/daa.vue')['default']
    ExploreContainer: typeof import('./components/ExploreContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/common/svg-icon.vue')['default']
  }
}
