name: Android APK构建

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: 设置Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: 安装pnpm
      run: npm install -g pnpm

    - name: 安装依赖
      run: pnpm install

    - name: 构建Web资源
      run: pnpm build
      
    - name: 安装Ionic CLI和Capacitor
      run: npm install -g @ionic/cli @capacitor/cli
      
    - name: 复制Web资源到Android平台
      run: |
        npx cap copy android
        npx cap sync android
      
    - name: 设置Gradle权限
      run: chmod +x ./android/gradlew
        
    # 如果需要构建Release版本，还需要配置签名密钥
    - name: 设置签名密钥
      if: github.ref == 'refs/heads/main'
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/my-release-key.keystore
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=my-release-key.keystore" >> android/key.properties
      
    - name: 构建Release APK
      if: github.ref == 'refs/heads/main'
      run: |
        cd android
        ./gradlew assembleRelease
        
    # - name: 上传Release APK
    #   if: github.ref == 'refs/heads/main'
    #   uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
    #   with:
    #     name: app-release
    #     path: android/app/build/outputs/apk/release/app-release.apk
        
    # 可选：自动更新apk-update.json文件
    - name: 更新APK信息
      if: github.ref == 'refs/heads/main'
      run: |
        APK_SIZE=$(stat -c%s "android/app/build/outputs/apk/release/app-release.apk")
        APK_SHA256=$(sha256sum "android/app/build/outputs/apk/release/app-release.apk" | cut -d' ' -f1)
        VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
        # 更新apk-update.json文件
        cat > public/apk-update.json << EOL
        {
          "android": {
            "version": "$VERSION",
            "minVersion": "0.0.1",
            "url": "http://117.72.49.27/downloads/be-cash-$VERSION.apk",
            "size": $APK_SIZE,
            "sha256": "$APK_SHA256",
            "isCritical": false
          }
        }
        EOL
        
        # 重命名APK文件
        mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/be-cash-$VERSION.apk
        
        # 添加调试信息
        echo "APK 文件已移动到:"
        ls -la android/app/build/outputs/apk/release/
        
    # 新增一个步骤：将文件移动到临时目录以便上传
    - name: 准备上传文件
      if: github.ref == 'refs/heads/main'
      run: |
        # 创建临时目录
        mkdir -p ./upload_temp
        # 复制文件到临时目录
        cp android/app/build/outputs/apk/release/be-cash-${{ env.VERSION }}.apk ./upload_temp/
        cp public/apk-update.json ./upload_temp/
        # 显示临时目录内容
        echo "准备上传的文件:"
        ls -la ./upload_temp/

    # 修改上传步骤
    - name: 上传APK到服务器
      if: github.ref == 'refs/heads/main'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "./upload_temp/*"  # 从临时目录上传所有文件
        target: "/home/be-cash/downloads/"
        strip_components: 1  # 只去掉 upload_temp 这一级目录

    - name: 查看生成的文件
      if: github.ref == 'refs/heads/main'
      run: |
        ls -la android/app/build/outputs/apk/release/
        # 验证APK是否已签名
        jarsigner -verify -verbose android/app/build/outputs/apk/release/*.apk