name: 构建发布到云服务器

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 安装pnpm
      run: npm install -g pnpm

    - name: 安装依赖
      run: pnpm install

    - name: 构建项目
      run: pnpm build

    - name: 上传文件到云服务器
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # 把 dist 目录下的所有文件上传到云服务器的 /home/be-cash 目录下，不包含 dist 目录
        source: "dist/*"
        target: "/home/be-cash/"
    
    - name: 重启 Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          sudo systemctl restart nginx
